### ISSUE TITLE
fallback Mp3 Firefox

### ISSUE THREAD

**Issue by generaid** [aFarkas/jMediaelement#10]
Hi Alex,
thanks for all the players! I have a problem with MP3 in Firefox. Unfortunately, the fall-back starts (JW player) does not. The Flash Player is not included.
Interestingly, "$ support.audio ($('< audio />')[ = 0] canPlayType);.." Also returns true.

Thanks

**Comment by generaid** [comment]
The Flash Player is still involved. But the stream via http He constantly interrupts and starts all over again. This behavior is only in Firefox. IE9, Safari, Chrome and Opera everything is running perfectly.

May lie in the buffer from the Flash Player?

**Comment by aFarkas** [comment]
Thanks for your bugreport. Could you please generate a testcase for me, so that I can see the bug.

**Comment by generaid** [comment]
I can go to generaid.de/de/music.html. You can find stream from last.fm.

**Comment by aFarkas** [comment]
Ok, there are two issues:
1. update your jwplayer, there seems to be a bug with older version of jwplayer. This should fix the most obvious bug. 
2. it is not allowed to change some styles of flash and its parents (overflow, position etc.). A simple way to achieve this for you, is to place the audio-element somewhere else (i.e. append it to the bottom of your body) and use the data-controls attribute to link your mediaplayer including your playlist with your audio element.

please let me know, wether this helped, so I can close this issue

**Comment by generaid** [comment]
Thanks for the reply, it is now. I had the playlist explicitly outside the "div class="media-player"" place. But what is still not in Firefox, the feature "getFormattedDuration ()". But I think this is due to the sandbox from Flashplayer.

Thanks for the help

**Comment by generaid** [comment]
Check out http://sefo.plakton.de http://iyon.plakton.de  ;)

Thanks for all...

-----Ursprüngliche Nachricht-----
Von: Alexander Farkas [mailto:reply@reply.github.com] 
Gesendet: Montag, 26. September 2011 08:35
An: generaid
Betreff: Re: [jMediaelement] fallback Mp3 Firefox (#10)

Thanks for your bugreport. Could you please generate a testcase for me, so that I can see the bug.

##
